<?php //[STAMP] 1521827799605df85bdd7e0c960e9361
namespace _generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

/**
 * Class FunctionalTesterActions
 * @package _generated
 */
trait FunctionalTesterActions {
	/**
	 * @return \Codeception\Scenario
	 */
	abstract protected function getScenario();


}
